/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/builds` | `/builds`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/builds/new` | `/builds/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/engines` | `/engines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/transmissions` | `/transmissions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/vehicles` | `/vehicles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/builds/[buildId]` | `/builds/[buildId]`, params: Router.UnknownInputParams & { buildId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/builds` | `/builds`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/builds/new` | `/builds/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/engines` | `/engines`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/transmissions` | `/transmissions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/vehicles` | `/vehicles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/builds/[buildId]` | `/builds/[buildId]`, params: Router.UnknownOutputParams & { buildId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/builds${`?${string}` | `#${string}` | ''}` | `/builds${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/builds/new${`?${string}` | `#${string}` | ''}` | `/builds/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/engines${`?${string}` | `#${string}` | ''}` | `/engines${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/transmissions${`?${string}` | `#${string}` | ''}` | `/transmissions${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/vehicles${`?${string}` | `#${string}` | ''}` | `/vehicles${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/builds` | `/builds`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/builds/new` | `/builds/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/engines` | `/engines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/transmissions` | `/transmissions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/vehicles` | `/vehicles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | `${'/(app)'}/builds/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/builds/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/builds/[buildId]` | `/builds/[buildId]`, params: Router.UnknownInputParams & { buildId: string | number; } };
    }
  }
}
