"""Add expanded spec fields and data provenance

Revision ID: 8e125203e866
Revises: 
Create Date: 2026-02-03 21:46:53.608185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e125203e866'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engines', sa.Column('displacement_liters', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('compression_ratio', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('valve_train', sa.String(length=50), nullable=True))
    op.add_column('engines', sa.Column('bore_mm', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('stroke_mm', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('balance_type', sa.String(length=50), nullable=True))
    op.add_column('engines', sa.Column('cam_intake_lift_in', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('cam_exhaust_lift_in', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('cam_intake_duration_deg', sa.Integer(), nullable=True))
    op.add_column('engines', sa.Column('cam_exhaust_duration_deg', sa.Integer(), nullable=True))
    op.add_column('engines', sa.Column('redline_rpm', sa.Integer(), nullable=True))
    op.add_column('engines', sa.Column('idle_rpm', sa.Integer(), nullable=True))
    op.add_column('engines', sa.Column('oil_pan_depth_in', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('oil_pan_type', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('front_accessory_drive_depth_in', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('cooling_system_type', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('thermostat_temp_f', sa.Integer(), nullable=True))
    op.add_column('engines', sa.Column('exhaust_port_shape', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('exhaust_header_primary_od_in', sa.Float(), nullable=True))
    op.add_column('engines', sa.Column('recommended_radiator_rows', sa.Integer(), nullable=True))
    op.add_column('engines', sa.Column('can_bus_protocol', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('ecu_type', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('starter_position', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('distributor_type', sa.String(length=100), nullable=True))
    op.add_column('engines', sa.Column('data_sources', sa.JSON(), nullable=True))
    op.add_column('engines', sa.Column('data_source_notes', sa.Text(), nullable=True))
    op.add_column('transmissions', sa.Column('trans_type', sa.String(length=50), nullable=True))
    op.add_column('transmissions', sa.Column('gear_count', sa.Integer(), nullable=True))
    op.add_column('transmissions', sa.Column('gear_ratios', sa.JSON(), nullable=True))
    op.add_column('transmissions', sa.Column('input_shaft_spline', sa.String(length=100), nullable=True))
    op.add_column('transmissions', sa.Column('output_shaft_spline', sa.String(length=100), nullable=True))
    op.add_column('transmissions', sa.Column('max_torque_capacity_lb_ft', sa.Integer(), nullable=True))
    op.add_column('transmissions', sa.Column('shift_linkage_type', sa.String(length=100), nullable=True))
    op.add_column('transmissions', sa.Column('crossmember_drop_in', sa.Float(), nullable=True))
    op.add_column('transmissions', sa.Column('tailhousing_length_in', sa.Float(), nullable=True))
    op.add_column('transmissions', sa.Column('speedometer_drive', sa.String(length=100), nullable=True))
    op.add_column('transmissions', sa.Column('data_sources', sa.JSON(), nullable=True))
    op.add_column('transmissions', sa.Column('data_source_notes', sa.Text(), nullable=True))
    # password_hash already removed in production (Supabase Auth handles passwords)
    # op.drop_column('users', 'password_hash')
    op.add_column('vehicles', sa.Column('engine_bay_length_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_bay_width_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_bay_height_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('firewall_to_radiator_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('driveline_angle_deg', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_tunnel_width_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_tunnel_height_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('curb_weight_lbs', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('stock_weight_distribution_front_pct', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('steering_type', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('steering_clearance_notes', sa.String(length=500), nullable=True))
    op.add_column('vehicles', sa.Column('stock_ground_clearance_in', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('data_sources', sa.JSON(), nullable=True))
    op.add_column('vehicles', sa.Column('data_source_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'data_source_notes')
    op.drop_column('vehicles', 'data_sources')
    op.drop_column('vehicles', 'stock_ground_clearance_in')
    op.drop_column('vehicles', 'steering_clearance_notes')
    op.drop_column('vehicles', 'steering_type')
    op.drop_column('vehicles', 'stock_weight_distribution_front_pct')
    op.drop_column('vehicles', 'curb_weight_lbs')
    op.drop_column('vehicles', 'transmission_tunnel_height_in')
    op.drop_column('vehicles', 'transmission_tunnel_width_in')
    op.drop_column('vehicles', 'driveline_angle_deg')
    op.drop_column('vehicles', 'firewall_to_radiator_in')
    op.drop_column('vehicles', 'engine_bay_height_in')
    op.drop_column('vehicles', 'engine_bay_width_in')
    op.drop_column('vehicles', 'engine_bay_length_in')
    # op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('transmissions', 'data_source_notes')
    op.drop_column('transmissions', 'data_sources')
    op.drop_column('transmissions', 'speedometer_drive')
    op.drop_column('transmissions', 'tailhousing_length_in')
    op.drop_column('transmissions', 'crossmember_drop_in')
    op.drop_column('transmissions', 'shift_linkage_type')
    op.drop_column('transmissions', 'max_torque_capacity_lb_ft')
    op.drop_column('transmissions', 'output_shaft_spline')
    op.drop_column('transmissions', 'input_shaft_spline')
    op.drop_column('transmissions', 'gear_ratios')
    op.drop_column('transmissions', 'gear_count')
    op.drop_column('transmissions', 'trans_type')
    op.drop_column('engines', 'data_source_notes')
    op.drop_column('engines', 'data_sources')
    op.drop_column('engines', 'distributor_type')
    op.drop_column('engines', 'starter_position')
    op.drop_column('engines', 'ecu_type')
    op.drop_column('engines', 'can_bus_protocol')
    op.drop_column('engines', 'recommended_radiator_rows')
    op.drop_column('engines', 'exhaust_header_primary_od_in')
    op.drop_column('engines', 'exhaust_port_shape')
    op.drop_column('engines', 'thermostat_temp_f')
    op.drop_column('engines', 'cooling_system_type')
    op.drop_column('engines', 'front_accessory_drive_depth_in')
    op.drop_column('engines', 'oil_pan_type')
    op.drop_column('engines', 'oil_pan_depth_in')
    op.drop_column('engines', 'idle_rpm')
    op.drop_column('engines', 'redline_rpm')
    op.drop_column('engines', 'cam_exhaust_duration_deg')
    op.drop_column('engines', 'cam_intake_duration_deg')
    op.drop_column('engines', 'cam_exhaust_lift_in')
    op.drop_column('engines', 'cam_intake_lift_in')
    op.drop_column('engines', 'balance_type')
    op.drop_column('engines', 'stroke_mm')
    op.drop_column('engines', 'bore_mm')
    op.drop_column('engines', 'valve_train')
    op.drop_column('engines', 'compression_ratio')
    op.drop_column('engines', 'displacement_liters')
    # ### end Alembic commands ###
